menu:
  首页: /
  归档: /archives
  关于: /about
  

widgets:
- search
- weibo
- category
- tagcloud

excerpt_link: 阅读全文

plugins:
- hexo-generator-feed

twitter:
  username: tiannianshou
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook:
  twitter: true
  google:
  pinterest:

fancybox: true

google_analytics: UA-41207871-1
rss: http://blog.lyric.name/atom.xml
