menu:
  首页: /
  归档: /archives
  关于: /about
  

widgets:
- search
- category
- tagcloud
- weibo

excerpt_link: 阅读全文

plugins:
- hexo-generator-feed

twitter:
  username: tiannianshou
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook:
  twitter:
  google:
  pinterest:

fancybox: true

google_analytics: UA-67900219-1
rss: http://blog.lyric.name/atom.xml
